# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18140vdcMbhF43UuwfTguAgaZdsQfZgTq
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

BaseDados = pd.read_excel('Dados_Empresas_Energia.xlsx')
BaseDados.set_index("Data")

print(BaseDados.head())


plt.figure(figsize=(16, 7))
plt.plot(BaseDados.index, BaseDados['Petrobras'], color='green', alpha=0.7, linewidth=4)
plt.text(BaseDados.index[-1],BaseDados['Petrobras'].tail(1), "Petrobras", horizontalalignment='left', color='green')

for Coluna in BaseDados.columns[1:]:
  plt.plot(BaseDados.index, BaseDados[Coluna], color='black', alpha=0.7, linewidth=4)
  plt.text(BaseDados.index[-1],BaseDados[Coluna].tail(1),Coluna, horizontalalignment='left', color='black')



plt.style.use('classic')
plt.title("Análise das ações de empresas de energia")
plt.xlabel("Período")
plt.ylabel("Preço de Fechamento")

plt.show()